# pull official base image
FROM python:3.10.1-slim-buster

# set working directory
WORKDIR /app

# set environment variables
# PYTHONDONTWRITEBYTECODE: Prevents Python from writing pyc files to disc (equivalent to python -B option)
# PYTHONUNBUFFERED: Prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc \
  && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# add app
COPY . .

# add entrypoint.sh
# COPY ./entrypoint.sh .
# RUN chmod +x /app/entrypoint.sh

# run entrypoint.sh
# waits until postgres container is ready
# ENTRYPOINT ["/app/entrypoint.sh"]