version: '3.8'

services:

  web:
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8004:8000
    volumes:
      - ./:/app
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
    depends_on:
      - web-db

  web-db:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2